### PR TITLE
If you're going to be a shitty person at least put *some* level of effort in.

### PR DESCRIPTION
**Pull request by nrlsk**
what it says on the tin

### CODE REVIEW

**Comment by edubenetskiy** [comment]
+1, it would be much easier to use. I am currently stuck with an inability to serialize the enum.

**Comment by mersinvald** [comment]
I'd also implement `Ord` by hand, autoderive would yield incorrect comparison results.

**Comment by nrlsk** [comment]
@mersinvald very good point! I’ll be sure to hand implement that this evening when I’m free! Cheers!

**Comment by edubenetskiy** [comment]
@nrlsk yes, and please consider carefully whether `Male` should be first after sorting or `Female` should be second.

**Pull request merged**
